### Create Jane Doe
POST http://localhost:8000/v1/users
Content-Type: application/json

{
    "firstName": "Jane",
    "lastName": "Doe",
    "email": "jane.doe@example.com",
    "password": "SecurePassword123!"
}

### Create John Doe
POST http://localhost:8000/v1/users
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "john.doe@example.com",
    "password": "P@ssw0rd!"
}

POST http://localhost:8000/v1/users/create-many
Content-Type: application/json

{
    "users": [
        {
            "firstName": "Alice",
            "lastName": "Smith",
            "email": "alice.smith@example.com",
            "password": "AlicePassword123!"
        },
        {
            "firstName": "Bob",
            "lastName": "Johnson",
            "email": "bob.johnson@example.com",
            "password": "BobPassword123!"
        }
    ]
}