### Upload multiple files
POST http://localhost:8000/v1/uploads/files
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="files"; filename="sample.txt"
Content-Type: text/plain

< C:\Users\PiyalChatterjee\Documents\Projects\PIP\nestjs-backend\sample.txt
--boundary
Content-Disposition: form-data; name="files"; filename="sample.png"
Content-Type: image/png

< C:\Users\PiyalChatterjee\Documents\Projects\PIP\nestjs-backend\sample.png
--boundary--
